name: newgraph
channels:
  - conda-forge
  - defaults
dependencies:
  - make
  - wget
  - zip
  - unzip
  - parallel
  - cdo
  - libpq
  - gdal>=3.5
  - python=3.9
  - rasterio
  - pip
  - requests
  - owslib
  - geopandas>=0.10.2
  - psycopg2
  - sqlalchemy<2.0
  - geoalchemy2
  - jq
  - rasterstats
  - scikit-image
  - awscli
  - seaborn
  - pip:
      - bcdata==0.7.6
variables:
  PGHOST: localhost
  PGUSER: airvine
  PGPORT: 5432
  PGDATABASE: newgraph
  DATABASE_URL: postgresql://airvine@localhost:5432/newgraph
