name: test-dump
run-name: ${{ github.actor }} Test CWF db access via cabd processing server
on:
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}

jobs:
  dump:
    name: "Test CWF db access via cabd processing server"
    runs-on: ubuntu-latest
    environment: cabd
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Configure SSH
        run: |
          apt-get update
          apt-get install -y openssh-client
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/cabd.key
          chmod 600 ~/.ssh/cabd.key
          cat <<EOF > ~/.ssh/config
          Host cabd
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/cabd.key
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Try a query
        run: |
          ssh -o "StrictHostKeyChecking no" -i ~/.ssh/cabd.key $SSH_USER@$SSH_HOST 'psql $DATABASE_URL -c "SELECT aggregated_crossings_id FROM bcfishpass.crossings_vw LIMIT 1"'