name: fwapg container
run-name: ${{ github.actor }} run fwapg container as gha
on: workflow_dispatch
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    container: ghcr.io/smnorris/fwapg:main
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run GDAL Command
      run: jobs/test