name: Run latest gdal
run-name: ${{ github.actor }} Try installing and running latest gdal
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install GDAL
      run: |
        sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev
    - name: Run GDAL Command
      run: jobs/test