name: Load required data
run-name: ${{ github.actor }} load bcfishpass required data
on: workflow_dispatch
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run GDAL Command
      run: jobs/gradient_barriers