name: production-bcfishpass
run-name: ${{ github.actor }} Run bcfishpass on prod
on:
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  load-parameters:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run:  |
          cp parameters/example_newgraph/*csv parameters/
          make --debug=basic .make/parameters
  build-xings:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    needs: load-parameters
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run:  jobs/bcfishpass01_modelledcrossings
  prep:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    needs: build-xings
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run:  jobs/bcfishpass02_prep
  model:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    needs: prep
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            fetch-tags: true
            fetch-depth: 0
      - name: Run the jobs
        run:  |
          git config --global --add safe.directory /__w/bcfishpass/bcfishpass
          jobs/bcfishpass03_model
  release:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    needs: model
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run:  jobs/freshwater_fish_habitat_accessibility_model