name: production-load-static
run-name: ${{ github.actor }} load FWA and static data
on: workflow_dispatch
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  load-fwa:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run job script
      run: jobs/load_fwa
  load-static:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    needs: load-fwa
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run job script
      run: jobs/load_static
  load-veg:
    runs-on: ubuntu-latest
    environment: staging
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run job script
      run: jobs/whse_forest_vegetation.veg_comp_lyr_r1_poly