name: testing-bcfishpass-qa
run-name: ${{ github.actor }} Run bcfishpass on test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  load-parameters:
    runs-on: ubuntu-latest
    environment: testing
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run:  |
          cp parameters/example_newgraph/*csv parameters/
          make --debug=basic .make/parameters