name: test
run-name: ${{ github.actor }} test
on:
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run:  |
          # Fetch tags to ensure that git describe works correctly
          git fetch --tags

          # Use git describe to get the version information
          VERSION=$(git describe --tags --abbrev=0) # --tags includes all tags, --abbrev=0 gives the full tag
          COMMITS=$(git rev-list ${VERSION}..HEAD --count) # Count of commits since the last tag
          COMMIT_HASH=$(git rev-parse --short HEAD) # Short commit hash

          # Print version information
          echo "Version: ${VERSION}"
          echo "Commits since last tag: ${COMMITS}"
          echo "Commit hash: ${COMMIT_HASH}"